server:
  port: 8082

security:
  jwt:
    token:
      secret-key: secret-key

spring:
  application.name: PlayMasterApplication
  devtools:
    livereload:
      port: 12346
  cloud.stream:
    bindings:
      processPlaysAndMoves-in-0:
        destination: new-moves
        group: group1
        auto.offset.reset: latest
      processPlaysAndMoves-in-1:
        destination: new-plays
        group: group1
        auto.offset.reset: latest
      processPlaysAndMoves-out-0:
        destination: new-plays
      processPlaysAndMoves-out-1:
        destination: completed-moves
      processPlaysAndMoves-out-2:
        destination: completed-plays
      processStatePlay-in-0:
        destination: new-plays
        group: group2
        auto.offset.reset: latest
    function.definition: processPlaysAndMoves,processStatePlay
    kafka:
      streams.binder.configuration.application.server: localhost:18082
      binder:
        brokers: 127.0.0.1:9094,127.0.0.1:9095,127.0.0.1:9096
        replication-factor: 3
        configuration:
          auto.offset.reset: latest
      streams.binder:
        functions:
          processPlaysAndMoves:
            applicationId: app_play_master_processPlaysAndMoves
          processStatePlay:
            applicationId: app_play_master_processStatePlay
        brokers: 127.0.0.1:9094,127.0.0.1:9095,127.0.0.1:9096
        deserialization-exception-handler: logandfail
        stateStoreRetry:
          maxAttempts: 3
          backoff-period: 5000
        configuration:
          #application.server: localhost:9094
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          commit.interval.ms: 1000